version: '3'
services:
  web:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid ; yarn install ; bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/application:cached
    ports:
      - "3000:3000"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
